[features]
seeds = false
skip-lint = false
[programs.localnet]
cryptopayly = "2fRi7Li4m9hc71UW6iRJLBTiPWfYxbL9CxAzbeLinHHT"

[programs.devnet]
cryptopayly = "2fRi7Li4m9hc71UW6iRJLBTiPWfYxbL9CxAzbeLinHHT"

[programs.mainnet]
cryptopayly = "2fRi7Li4m9hc71UW6iRJLBTiPWfYxbL9CxAzbeLinHHT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andreyfrolov/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
copy-idl = "cp target/types/cryptopayly.ts app/src/constants/idl.ts"
